[package]
name = "vaporetto"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
byteorder = "1.4"
fst = "0.4"
crossbeam-channel = { version = "0.5", optional = true }
liblinear = { version = "1", optional = true }

[features]
default = ["model-quantize"]
model-quantize = []
multithreading = ["crossbeam-channel"]
train = ["liblinear"]
kytea = []
