[package]
name = "vaporetto"
version = "0.3.0"
edition = "2021"
authors = ["Koichi Akabe <vbkaisetsu@gmail.com>"]
description = "Vaporetto: a pointwise prediction based tokenizer"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/legalforce-research/vaporetto"
repository = "https://github.com/legalforce-research/vaporetto"
readme = "README.md"
keywords = ["japanese", "analyzer", "tokenizer", "morphological"]
categories = ["text-processing"]
autotests = false

[dependencies]
daachorse = "0.4.0"  # MIT or Apache-2.0
byteorder = "1.4"  # Unlicense or MIT

liblinear = { version = "1", optional = true }  # MIT

[features]
default = []
kytea = []
train = ["liblinear"]
portable-simd = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
