[package]
name = "vaporetto_wasm"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.75"
vaporetto = { path = "../vaporetto" }
js-sys = "0.3.52"
